---
title: "node level analysis"
output: html_notebook
---
node info
```{r}

node_info <- function(igraph){
  eigen=eigen_centrality(igraph, directed = FALSE, scale = FALSE,weights = abs(E(igraph)$weight), options = arpack_defaults)
  df2 <-data.frame("CC"= c(transitivity(igraph,type = "local",vids = V(igraph),weights = abs(E(igraph)$weight),isolates="zero")),
                   "bet"=c(betweenness(igraph,v = V(igraph),directed = FALSE, weights = 1/abs(E(igraph)$weight),normalized =F)),
                   "degree"=c(degree(igraph,v = V(igraph),mode ="all",loops = FALSE,normalized = F)),
                   "strength"=c(strength(igraph,vids = V(igraph),loops = FALSE)),
                   "eigen"=eigen$vector,
                   "nei"=influential::neighborhood.connectivity( igraph,vertices = V(igraph),mode = "all",verbose = FALSE))
  return(df2)}


evo_pos_node_info <- node_info(evo_positive_p_igraph)
evo_neg_node_info <- node_info(evo_negative_p_igraph)

unevo_pos_node_info <- node_info(unevo_positive_p_igraph)
unevo_neg_node_info <- node_info(unevo_negative_p_igraph)

WT_pos_node_info <- node_info(WT_positive_p_igraph)
WT_neg_node_info <- node_info(WT_negative_p_igraph)

evoWT_pos_node_info <- node_info(evoWT_positive_p_igraph)
evoWT_neg_node_info <- node_info(evoWT_negative_p_igraph)

mut_pos_node_info <- node_info(mut_positive_p_igraph)
mut_neg_node_info <- node_info(mut_negative_p_igraph)



CC_WT= transitivity(WT_positive_p_igraph,type = "global",vids = V(WT_positive_p_igraph),weights = abs(E(WT_positive_p_igraph)$weight),isolates="zero")

CC_unevo= transitivity(unevo_positive_p_igraph,type = "global",vids = V(unevo_positive_p_igraph),weights = abs(E(unevo_positive_p_igraph)$weight),isolates="zero")

CC_evo= transitivity(evo_positive_p_igraph,type = "global",vids = V(evo_positive_p_igraph),weights = abs(E(evo_positive_p_igraph)$weight),isolates="zero")

CC_evoWT= transitivity(evoWT_positive_p_igraph,type = "global",vids = V(evoWT_positive_p_igraph),weights = abs(E(evoWT_positive_p_igraph)$weight),isolates="zero")

CC_mut= transitivity(mut_positive_p_igraph,type = "global",vids = V(mut_positive_p_igraph),weights = abs(E(mut_positive_p_igraph)$weight),isolates="zero")


MyMerge       <- function(x, y){
  df            <- merge(x, y, by= "row.names", all.x= T, all.y= T)
  rownames(df)  <- df$Row.names
  df$Row.names  <- NULL
  return(df)
}

#positive

deg_pos_all<- Reduce(MyMerge, list(select(WT_pos_node_info,"degree"), select(unevo_pos_node_info,"degree"), select(evo_pos_node_info,"degree"), select(evoWT_pos_node_info,"degree"),select(mut_pos_node_info,"degree")))%>% 
  `colnames<-`(c("WT","unevo","evo","evoWT","mut")) 

CC_pos_all<- Reduce(MyMerge, list(select(WT_pos_node_info,"CC"), select(unevo_pos_node_info,"CC"), select(evo_pos_node_info,"CC"), select(evoWT_pos_node_info,"CC"),select(mut_pos_node_info,"CC")))%>% 
  `colnames<-`(c("WT","unevo","evo","evoWT","mut")) 

#deleting nodes with degree<10 for CC distribution
CC_pos_all_high_degree <- CC_pos_all
for (met in c(1:nrow(CC_pos_all_high_degree))){
  for (bac in c(1:ncol(CC_pos_all_high_degree))){
    if (is.na(CC_pos_all_high_degree[met,bac])==FALSE & deg_pos_all[met,bac]<10){
      CC_pos_all_high_degree[met,bac] <- NA
    }}}


bet_pos_all<- Reduce(MyMerge, list(select(evo_pos_node_info,"bet"), select(unevo_pos_node_info,"bet"), select(evoWT_pos_node_info,"bet"), select(WT_pos_node_info,"bet"),select(mut_pos_node_info,"bet")))%>%
  `colnames<-`(c("evo","unevo","evoWT","WT","mut"))


strength_pos_all<- Reduce(MyMerge, list(select(evo_pos_node_info,"strength"), select(unevo_pos_node_info,"strength"), select(evoWT_pos_node_info,"strength"), select(WT_pos_node_info,"strength"),select(mut_pos_node_info,"strength")))%>%
  `colnames<-`(c("evo","unevo","evoWT","WT","mut"))

eigen_pos_all<- Reduce(MyMerge, list(select(evo_pos_node_info,"eigen"), select(unevo_pos_node_info,"eigen"), select(evoWT_pos_node_info,"eigen"), select(WT_pos_node_info,"eigen"),select(mut_pos_node_info,"eigen")))%>%
  `colnames<-`(c("evo","unevo","evoWT","WT","mut"))

neib_pos_all<- Reduce(MyMerge, list(select(WT_pos_node_info,"nei"), select(unevo_pos_node_info,"nei"), select(evo_pos_node_info,"nei"), select(evoWT_pos_node_info,"nei"),select(mut_pos_node_info,"nei")))%>% 
  `colnames<-`(c("WT","unevo","evo","evoWT","mut")) 

#negative

bet_neg_all<- Reduce(MyMerge, list(select(evo_neg_node_info,"bet"), select(unevo_neg_node_info,"bet"), select(evoWT_neg_node_info,"bet"), select(WT_neg_node_info,"bet"),select(mut_neg_node_info,"bet")))%>%
  `colnames<-`(c("evo","unevo","evoWT","WT","mut"))

deg_neg_all<- Reduce(MyMerge, list(select(evo_neg_node_info,"degree"), select(unevo_neg_node_info,"degree"), select(evoWT_neg_node_info,"degree"), select(WT_neg_node_info,"degree"),select(mut_neg_node_info,"degree")))%>%
  `colnames<-`(c("evo","unevo","evoWT","WT","mut"))

strength_neg_all<- Reduce(MyMerge, list(select(evo_neg_node_info,"strength"), select(unevo_neg_node_info,"strength"), select(evoWT_neg_node_info,"strength"), select(WT_neg_node_info,"strength"),select(mut_neg_node_info,"strength")))%>%
  `colnames<-`(c("evo","unevo","evoWT","WT","mut"))

eigen_neg_all<- Reduce(MyMerge, list(select(evo_neg_node_info,"eigen"), select(unevo_neg_node_info,"eigen"), select(evoWT_neg_node_info,"eigen"), select(WT_neg_node_info,"eigen"),select(mut_neg_node_info,"eigen")))%>%
  `colnames<-`(c("evo","unevo","evoWT","WT","mut"))

neib_neg_all<- Reduce(MyMerge, list(select(WT_neg_node_info,"nei"), select(unevo_neg_node_info,"nei"), select(evo_neg_node_info,"nei"), select(evoWT_neg_node_info,"nei"),select(mut_neg_node_info,"nei")))%>% 
  `colnames<-`(c("WT","unevo","evo","evoWT","mut")) 

#distribution plots- 
#positive

CC_plot<-CC_pos_all_high_degree %>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "CC")%>% ggplot(aes(x=CC,fill=Name)) + geom_histogram( 
  color="black", alpha=0.7 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evoWT","mut"))) + labs(title="Node CC distribution (positive)", x="Clustering coefficient", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#d11141","mut"="#9999CC"))
CC_plot

ggsave(filename="plots_and_tables/plots/CC_high_degree_pos_PCLRC.pdf", plot = CC_plot, width=6, height=4)

mean_CC <- colMeans(CC_pos_all_high_degree, na.rm = TRUE, dims = 1)
library(matrixStats)
sd <- colSds(as.matrix(CC_pos_all_high_degree),na.rm=TRUE)



bet_plot<-bet_pos_all%>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "bet") %>% ggplot(aes(x=bet,fill=Name)) + geom_histogram(color="black", alpha=0.7 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evolved-WT","mut"))) + labs(title="Node betweenness distribution", x="node Betweenness", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#edae49","mut"="#9999CC"))
bet_plot


ggsave(filename="plots_and_tables/plots/bet_pos_PCLRC.pdf", plot = bet_plot, width=6, height=4)

degree_plot<-deg_pos_all %>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "degree")%>%ggplot(aes(x=degree,fill=Name)) + geom_histogram(color="black", alpha=0.7, linewidth=0.02) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evoWT","mut"))) + labs(title="Node degree distribution", x="Degree", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#d11141","mut"="#9999CC"))
degree_plot

ggsave(filename="plots_and_tables/plots/degree_pos_PCLRC.pdf", plot = degree_plot, width=6, height=4)

strength_plot<-strength_pos_all%>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "strength") %>% ggplot(aes(x=strength,fill=Name)) + geom_histogram(color="black", alpha=0.7 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evolved-WT","mut"))) + labs(title="Node strength distribution", x="Strength", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#edae49","mut"="#9999CC"))
strength_plot

ggsave(filename="plots_and_tables/plots/strength_pos_PCLRC.pdf", plot = strength_plot, width=6, height=4)


eigen_plot<-eigen_pos_all%>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "eigen") %>% ggplot(aes(x=eigen,fill=Name)) + geom_histogram(color="black", alpha=0.7 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evolved-WT","mut"))) + labs(title="Node eigen value distribution", x="Eigen value", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#edae49","mut"="#9999CC"))
eigen_plot

ggsave(filename="plots_and_tables/plots/eigen_pos_PCLRC.pdf", plot = eigen_plot, width=6, height=4)

nei_plot<-neib_pos_all%>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "nei") %>% ggplot(aes(x=nei,fill=Name))  + geom_histogram(color="black", alpha=0.7, linewidth=0.2 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evoWT","mut"))) + labs(title="Node negative neighborhood connectivity", x="Neighborhood Connectivity", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#d11141","mut"="#9999CC"))
nei_plot

ggsave(filename="plots_and_tables/plots/nei_pos_PCLRC.pdf", plot = nei_plot, width=6, height=4)


#negative
bet_plot<-bet_neg_all%>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "bet") %>% ggplot(aes(x=bet,fill=Name)) + geom_histogram(color="black", alpha=0.7 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evolved-WT","mut"))) + labs(title="Node betweenness distribution", x="node Betweenness", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#edae49","mut"="#9999CC"))
bet_plot


ggsave(filename="plots_and_tables/plots/bet_neg_PCLRC.pdf", plot = bet_plot, width=6, height=4)

degree_plot<-deg_neg_all %>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "degree")%>%ggplot(aes(x=degree,fill=Name)) + geom_histogram(color="black", alpha=0.7, linewidth=0.02) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evoWT","mut"))) + labs(title="Node degree distribution", x="Degree", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#d11141","mut"="#9999CC"))
degree_plot

ggsave(filename="plots_and_tables/plots/degree_neg_PCLRC.pdf", plot = degree_plot, width=6, height=4)

strength_plot<-strength_neg_all%>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "strength") %>% ggplot(aes(x=strength,fill=Name)) + geom_histogram(color="black", alpha=0.7 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evolved-WT","mut"))) + labs(title="Node strength distribution", x="Strength", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#edae49","mut"="#9999CC"))
strength_plot

ggsave(filename="plots_and_tables/plots/strength_neg_PCLRC.pdf", plot = strength_plot, width=6, height=4)


eigen_plot<-eigen_neg_all%>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "eigen") %>% ggplot(aes(x=eigen,fill=Name)) + geom_histogram(color="black", alpha=0.7 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evolved-WT","mut"))) + labs(title="Node eigen value distribution", x="Eigen value", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#edae49","mut"="#9999CC"))
eigen_plot

ggsave(filename="plots_and_tables/plots/eigen_neg_PCLRC.pdf", plot = eigen_plot, width=6, height=4)

nei_plot<-neib_neg_all%>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "nei") %>% ggplot(aes(x=nei,fill=Name))  + geom_histogram(color="black", alpha=0.7, linewidth=0.2 ) +facet_grid(. ~ factor(Name, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evoWT","mut"))) + labs(title="Node negative neighborhood connectivity", x="Neighborhood Connectivity", y="Count")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3))+theme_minimal(base_size = 16)+ theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=0.3),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue", "evoWT"="#d11141","mut"="#9999CC"))
nei_plot

ggsave(filename="plots_and_tables/plots/nei_neg_PCLRC.pdf", plot = nei_plot, width=6, height=4)

#was deleted- degree vs. CC



#only top 5%- degree and neibor

hubs_degree_plot<-deg_pos_all %>% tibble::rownames_to_column(var = "Row")%>%pivot_longer(-Row, names_to = "Name", values_to = "degree")%>%
 arrange(desc(degree))%>% slice(1:round(nrow(deg_pos_all)/20,0)) %>% group_by(Name) %>%tally() %>%
  ggplot(aes(x=factor(Name, levels=c("WT","unevo","evo","evoWT","mut")),y=n, fill=Name))+ geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +labs(title="Top 5% positive degree nodes", x="Bacterial Strain", y="Count")+theme_minimal(base_size = 30)+theme(axis.text.x = element_text(face="bold"),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue","evoWT"="#d11141","mut"="#9999CC"))+scale_x_discrete(limits= c("WT","unevo","evo","evoWT","mut"),labels=c("WT" = "WT", "unevo" = "unevolved","evo" = "evolved","evoWT"="evoWT","mut"="mut"))
hubs_degree_plot

ggsave(filename="plots_and_tables/plots/hubs_degree_plot_pos.pdf", plot = hubs_degree_plot, width=12, height=4)


hubs_degree_plot<-deg_neg_all %>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "degree")%>%arrange(desc(degree))%>% slice(1:round(nrow(deg_pos_all)/20,0)) %>% group_by(Name) %>%tally() %>%ggplot(aes(x=factor(Name, levels=c("WT","unevo","evo","evoWT","mut")),y=n, fill=Name))+ geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +labs(title="Top 5% negative degree nodes", x="Bacterial Strain", y="Count")+theme_minimal(base_size = 30)+theme(axis.text.x = element_text(face="bold"),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue","evoWT"="#d11141","mut"="#9999CC"))+scale_x_discrete(limits= c("WT","unevo","evo","evoWT","mut"),labels=c("WT" = "WT", "unevo" = "unevolved","evo" = "evolved","evoWT"="evoWT","mut"="mut"))
hubs_degree_plot


ggsave(filename="plots_and_tables/plots/hubs_degree_plot_neg.pdf", plot = hubs_degree_plot, width=12, height=4)






hubs_nei_plot<-neib_pos_all %>% tibble::rownames_to_column(var = "Row")%>%pivot_longer(-Row, names_to = "Name", values_to = "nei")%>%
 arrange(desc(nei))%>% slice(1:round(nrow(neib_pos_all)/20,0)) %>% group_by(Name) %>%tally() %>%
  ggplot(aes(x=factor(Name, levels=c("WT","unevo","evo","evoWT","mut")),y=n, fill=Name))+ geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +labs(title="Top 5% positive NC nodes", x="Bacterial Strain", y="Count")+theme_minimal(base_size = 30)+theme(axis.text.x = element_text(face="bold"),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue","evoWT"="#d11141","mut"="#9999CC"))+scale_x_discrete(limits= c("WT","unevo","evo","evoWT","mut"),labels=c("WT" = "WT", "unevo" = "unevolved","evo" = "evolved","evoWT"="evoWT","mut"="mut"))
hubs_nei_plot

ggsave(filename="plots_and_tables/plots/hubs_nei_plot_pos.pdf", plot = hubs_nei_plot, width=12, height=4)


hubs_nei_plot<-neib_neg_all %>% tibble::rownames_to_column(var = "Row") %>%pivot_longer(-Row, names_to = "Name", values_to = "nei")%>%arrange(desc(nei))%>% slice(1:round(nrow(neib_neg_all)/20,0)) %>% group_by(Name) %>%tally() %>%ggplot(aes(x=factor(Name, levels=c("WT","unevo","evo","evoWT","mut")),y=n, fill=Name))+ geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +labs(title="Top 5% negative NC nodes", x="Bacterial Strain", y="Count")+theme_minimal(base_size = 30)+theme(axis.text.x = element_text(face="bold"),legend.position="none") +scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue","evoWT"="#d11141","mut"="#9999CC"))+scale_x_discrete(limits= c("WT","unevo","evo","evoWT","mut"),labels=c("WT" = "WT", "unevo" = "unevolved","evo" = "evolved","evoWT"="evoWT","mut"="mut"))
hubs_degree_plot


ggsave(filename="plots_and_tables/plots/hubs_nei_plot_neg.pdf", plot = hubs_nei_plot, width=12, height=4)


```

scatter plots
```{r}


#deg pos- change bacteria 
 ggplot(deg_pos_all, aes(x=deg_pos_all$evo, y=deg_pos_all$evoWT)) +
  geom_point(color = "darkcyan", size=1) + labs(title="evo vs. evoWT", x="evo", y="evoWT")+theme(plot.title = element_text(size = 35, face = "bold"),text = element_text(size = 20))+ theme(aspect.ratio=1)+geom_abline()+xlim(0,0.18)+ylim(0,0.18)


#deg neg- change bacteria 
ggplot(deg_neg_all, aes(x=deg_neg_all$evo, y=deg_neg_all$evoWT)) +
  geom_point(color = "darkcyan", size=1) + labs(title="evo vs. evoWT", x="evo", y="evoWT")+theme(plot.title = element_text(size = 35, face = "bold"),text = element_text(size = 20))+ theme(aspect.ratio=1)+geom_abline()+xlim(0,0.1)+ylim(0,0.1)

#CC- change bacteria
CC_plot <- ggplot(CC_pos_all_high_degree, aes(x=CC_pos_all_high_degree$mut, y=CC_pos_all_high_degree$evoWT)) +
  geom_point(color = "darkcyan", size=1) + labs(title="mut vs. evoWT", x="mut", y="evoWT")+theme(plot.title = element_text(size = 35, face = "bold"),text = element_text(size = 20))+ theme(aspect.ratio=1)+geom_abline()
CC_plot

#bet- change bacteria
bet_plot <- ggplot(bet_pos_all, aes(x=bet_pos_all$unevo, y=bet_pos_all$evoWT)) +
  geom_point(color = "darkcyan", size=1) + labs(title="unevo vs. evoWT", x="unevo", y="evoWT")+theme(plot.title = element_text(size = 35, face = "bold"),text = element_text(size = 20))+xlim(0,0.05)+ylim(0,0.05)
bet_plot


```

sam and meth corrs
```{r}


#SAM meth common correlation

SAM_pos_neg <- lapply(list(common_WT_pos,common_WT_neg,common_unevo_pos,common_unevo_neg,common_evo_pos,common_evo_neg,common_evoWT_pos,common_evoWT_neg,common_mut_pos,common_mut_neg),function(x) filter(x,M1=="cluster_82"|M2=="cluster_82"))



SAM_pos_neg_df <- data.frame(matrix(sapply(SAM_pos_neg, nrow),ncol=2, byrow=T)) %>% add_column(bact=c("WT","unevo","evo","evoWT","mut"))%>%`colnames<-`(c("pos","neg","bact"))


#positive

#to add the amount of common between the networks
common_pos_with_WT <- c(NA, nrow(common_corrs(SAM_pos_neg[[1]],SAM_pos_neg[[3]])), nrow(common_corrs(SAM_pos_neg[[1]],SAM_pos_neg[[5]])), nrow(common_corrs(SAM_pos_neg[[1]],SAM_pos_neg[[7]])),nrow(common_corrs(SAM_pos_neg[[1]],SAM_pos_neg[[9]])))

common_pos_with_unevo <- c(nrow(common_corrs(SAM_pos_neg[[3]],SAM_pos_neg[[1]])), NA, nrow(common_corrs(SAM_pos_neg[[3]],SAM_pos_neg[[5]])), nrow(common_corrs(SAM_pos_neg[[3]],SAM_pos_neg[[7]])),nrow(common_corrs(SAM_pos_neg[[3]],SAM_pos_neg[[9]])))

common_pos_with_evo <- c(nrow(common_corrs(SAM_pos_neg[[5]],SAM_pos_neg[[1]])), nrow(common_corrs(SAM_pos_neg[[5]],SAM_pos_neg[[3]])),NA, nrow(common_corrs(SAM_pos_neg[[5]],SAM_pos_neg[[7]])),nrow(common_corrs(SAM_pos_neg[[5]],SAM_pos_neg[[9]])))

common_pos_with_evoWT <- c(nrow(common_corrs(SAM_pos_neg[[7]],SAM_pos_neg[[1]])), nrow(common_corrs(SAM_pos_neg[[7]],SAM_pos_neg[[3]])), nrow(common_corrs(SAM_pos_neg[[7]],SAM_pos_neg[[5]])),NA,nrow(common_corrs(SAM_pos_neg[[7]],SAM_pos_neg[[9]])))

common_pos_with_mut <- c(nrow(common_corrs(SAM_pos_neg[[9]],SAM_pos_neg[[1]])), nrow(common_corrs(SAM_pos_neg[[9]],SAM_pos_neg[[3]])), nrow(common_corrs(SAM_pos_neg[[9]],SAM_pos_neg[[5]])),nrow(common_corrs(SAM_pos_neg[[9]],SAM_pos_neg[[7]])),NA)

SAM_corrs_pos <- ggplot(data=melt(SAM_pos_neg_df)%>%filter(variable=="pos"), aes(x=factor(bact, levels=c("WT", "unevo", "evo", "evoWT", "mut"),labels=c("WT","unevolved","evolved","evolved-WT","mut")), y=value, fill=bact)) +geom_bar(stat="identity", position=position_dodge(),width = 0.7,color="black") +labs(title=" ", x="\nBacterial Strain", y="Count\n")+theme_minimal()+theme(axis.text.x = element_text(size=27,face="bold"),axis.text.y =element_text(size=22), axis.title=element_text(size=32),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue",evoWT="#d11141", mut="#9999CC"))+geom_errorbar(aes(y = common_pos_with_WT, ymin = common_pos_with_WT, ymax = common_pos_with_WT), color="coral",lty=2,linewidth=1.5,width=0.7) + 
  geom_errorbar(aes(y=common_pos_with_unevo,ymin=common_pos_with_unevo,ymax=common_pos_with_unevo),color="#339900",lty=2,linewidth=1.5,width=0.7)+
  geom_errorbar(aes(y=common_pos_with_evo,ymin=common_pos_with_evo,ymax=common_pos_with_evo),color="cornflowerblue",lty=2,linewidth=1.5,width=0.7)+
  geom_errorbar(aes(y=common_pos_with_evoWT,ymin=common_pos_with_evoWT,ymax=common_pos_with_evoWT),color="#d11141",lty=2,linewidth=1.5,width=0.7)+
  geom_errorbar(aes(y=common_pos_with_mut,ymin=common_pos_with_mut,ymax=common_pos_with_mut),color="#9999CC",lty=2,linewidth=1.5,width=0.7)

SAM_corrs_pos

ggsave("plots_and_tables/plots/SAM_corrs_pos_PCLRC.pdf", height=7, width=12)

#negative

common_neg_with_WT <- c(NA, nrow(common_corrs(SAM_pos_neg[[2]],SAM_pos_neg[[4]])), nrow(common_corrs(SAM_pos_neg[[2]],SAM_pos_neg[[6]])), nrow(common_corrs(SAM_pos_neg[[2]],SAM_pos_neg[[8]])), nrow(common_corrs(SAM_pos_neg[[2]],SAM_pos_neg[[10]])))

common_neg_with_unevo <- c(nrow(common_corrs(SAM_pos_neg[[4]],SAM_pos_neg[[2]])), NA, nrow(common_corrs(SAM_pos_neg[[4]],SAM_pos_neg[[6]])), nrow(common_corrs(SAM_pos_neg[[4]],SAM_pos_neg[[8]])),nrow(common_corrs(SAM_pos_neg[[4]],SAM_pos_neg[[10]])))

common_neg_with_evo <- c(nrow(common_corrs(SAM_pos_neg[[6]],SAM_pos_neg[[2]])), nrow(common_corrs(SAM_pos_neg[[6]],SAM_pos_neg[[4]])),NA, nrow(common_corrs(SAM_pos_neg[[6]],SAM_pos_neg[[8]])),nrow(common_corrs(SAM_pos_neg[[6]],SAM_pos_neg[[10]])))

common_neg_with_evoWT <- c(nrow(common_corrs(SAM_pos_neg[[8]],SAM_pos_neg[[2]])), nrow(common_corrs(SAM_pos_neg[[8]],SAM_pos_neg[[4]])), nrow(common_corrs(SAM_pos_neg[[8]],SAM_pos_neg[[6]])),NA,nrow(common_corrs(SAM_pos_neg[[8]],SAM_pos_neg[[10]])))

common_neg_with_mut <- c(nrow(common_corrs(SAM_pos_neg[[10]],SAM_pos_neg[[2]])), nrow(common_corrs(SAM_pos_neg[[10]],SAM_pos_neg[[4]])), nrow(common_corrs(SAM_pos_neg[[10]],SAM_pos_neg[[6]])),nrow(common_corrs(SAM_pos_neg[[10]],SAM_pos_neg[[8]])),NA)


SAM_corrs_neg <- ggplot(data=melt(SAM_pos_neg_df)%>%filter(variable=="neg"), aes(x=factor(bact, levels=c("WT", "unevo", "evo", "evoWT","mut"),labels=c("WT","unevolved","evolved","evolved-WT","mut")), y=value, fill=bact)) +geom_bar(stat="identity", position=position_dodge(),width = 0.7,color="black") +labs(title=" ", x="\nBacterial Strain", y="Count\n")+theme_minimal()+theme(axis.text.x = element_text(size=27,face="bold"),axis.text.y =element_text(size=22), axis.title=element_text(size=32),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevo="#339900",evo="cornflowerblue",evoWT="#d11141"))+  scale_y_continuous(breaks=seq(from = 0, to = 13, by = 3)
)+
  geom_errorbar(aes(y = common_neg_with_WT, ymin = common_neg_with_WT, ymax = common_neg_with_WT), color="coral",lty=2,linewidth=1.5,width=0.7) + 
  geom_errorbar(aes(y=common_neg_with_unevo,ymin=common_neg_with_unevo,ymax=common_neg_with_unevo),color="#339900",lty=2,linewidth=1.5,width=0.7)+
  geom_errorbar(aes(y=common_neg_with_evo,ymin=common_neg_with_evo,ymax=common_neg_with_evo),color="cornflowerblue",lty=2,linewidth=1.5,width=0.7)+
  geom_errorbar(aes(y=common_neg_with_evoWT,ymin=common_neg_with_evoWT,ymax=common_neg_with_evoWT),color="#d11141",lty=2,linewidth=1.5,width=0.7)+
  geom_errorbar(aes(y=common_neg_with_mut,ymin=common_neg_with_mut,ymax=common_neg_with_mut),color="#9999CC",lty=2,linewidth=1.5,width=0.7)


SAM_corrs_neg


ggsave("plots_and_tables/plots/SAM_corrs_neg_PCLRC.pdf", height=7, width=12)


#methionine?

meth_3 <- rbind(change_in_corrs(common_WT_pos,WT_positive_p_1,WT_positive_p_2,"cluster_34"
),change_in_corrs(common_unevo_pos,unevo_positive_p_1,unevo_positive_p_2,"cluster_34"),change_in_corrs(common_evo_pos,evo_positive_p_1,evo_positive_p_2,"cluster_34"),change_in_corrs(common_evoWT_pos,evoWT_positive_p_1,evoWT_positive_p_2,"cluster_34"))%>%`rownames<-`(c("WT","unevo","evo","evoWT"))




```


SAM and SAM related metabolites characteristics

```{r}
met <- list(SAM="cluster_82",meth="cluster_34", cystein="cluster_142",spermidine="cluster_6",homoserine="cluster_131",MTA="cluster_71",putrescine="cluster_320")

char <-  data.frame(matrix(nrow=0,ncol=7)) 

myobjects <- list(WT_pos=WT_pos_node_info,WT_neg=WT_neg_node_info, unevo_pos=unevo_pos_node_info,unevo_neg=unevo_neg_node_info,evo_pos=evo_pos_node_info,evo_neg=evo_neg_node_info, evoWT_pos=evoWT_pos_node_info,evoWT_neg=evoWT_neg_node_info,mut_pos=mut_pos_node_info,mut_neg=mut_neg_node_info)

for (m in 1:length(met)){
  for (data in 1:length(myobjects)){
    row=cbind(met[[m]],names(met)[m],names(myobjects)[data],myobjects[[data]][met[[m]],])
    char <- rbind(char, row)
  }}
rownames(char)<-NULL
char <- char %>% separate(`names(myobjects)[data]`, c('bact', 'layer'))



```

annotated metabolites amounts
```{r}
#amounts

set_tbl<-read_excel("unique_19_each_585_new.xlsx", sheet="585_1")
set_tbl[,6:100][set_tbl[,6:100 ]==0]<- NA
evo_set_tbl <-set_tbl[,6:24] %>%cbind(set_tbl$cluster)
evoWT_set_tbl<-set_tbl[,25:43] %>%cbind(set_tbl$cluster)
unevo_set_tbl<-set_tbl[,63:81] %>%cbind(set_tbl$cluster)
WT_set_tbl<-set_tbl[,82:100] %>%cbind(set_tbl$cluster)
mut_set_tbl<-set_tbl[,44:62]%>%cbind(set_tbl$cluster)


WT_set_tbl <-WT_set_tbl %>% tibble::column_to_rownames(var="set_tbl$cluster")%>%data.matrix()%>%t()
evo_set_tbl <-evo_set_tbl %>% tibble::column_to_rownames(var="set_tbl$cluster")%>%data.matrix()%>%t()
unevo_set_tbl <-unevo_set_tbl %>% tibble::column_to_rownames(var="set_tbl$cluster")%>%data.matrix()%>%t()
evoWT_set_tbl <-evoWT_set_tbl %>% tibble::column_to_rownames(var="set_tbl$cluster")%>%data.matrix()%>%t()
mut_set_tbl <-mut_set_tbl %>% tibble::column_to_rownames(var="set_tbl$cluster")%>%data.matrix()%>%t()

mean_sd_addiotinal_metabolites <- data.frame(matrix(c(mean(WT_set_tbl[,"cluster_142"]),sd(WT_set_tbl[,"cluster_142"]),mean(WT_set_tbl[,"cluster_6"]),sd(WT_set_tbl[,"cluster_6"]),mean(WT_set_tbl[,"cluster_131"]),sd(WT_set_tbl[,"cluster_131"]),mean(WT_set_tbl[,"cluster_71"]),sd(WT_set_tbl[,"cluster_71"]),mean(WT_set_tbl[,"cluster_320"]),sd(WT_set_tbl[,"cluster_320"]),mean(unevo_set_tbl[,"cluster_142"]),sd(unevo_set_tbl[,"cluster_142"]),mean(unevo_set_tbl[,"cluster_6"]),sd(unevo_set_tbl[,"cluster_6"]),mean(unevo_set_tbl[,"cluster_131"]),sd(unevo_set_tbl[,"cluster_131"]),mean(unevo_set_tbl[,"cluster_71"]),sd(unevo_set_tbl[,"cluster_71"]),mean(unevo_set_tbl[,"cluster_320"]),sd(unevo_set_tbl[,"cluster_320"]), mean(evo_set_tbl[,"cluster_142"]),sd(evo_set_tbl[,"cluster_142"]),mean(evo_set_tbl[,"cluster_6"]),sd(evo_set_tbl[,"cluster_6"]),mean(evo_set_tbl[,"cluster_131"]),sd(evo_set_tbl[,"cluster_131"]),mean(evo_set_tbl[,"cluster_71"]),sd(evo_set_tbl[,"cluster_71"]),mean(evo_set_tbl[,"cluster_320"]),sd(evo_set_tbl[,"cluster_320"]),mean(evoWT_set_tbl[,"cluster_142"]),sd(evoWT_set_tbl[,"cluster_142"]),mean(evoWT_set_tbl[,"cluster_6"]),sd(evoWT_set_tbl[,"cluster_6"]),mean(evoWT_set_tbl[,"cluster_131"]),sd(evoWT_set_tbl[,"cluster_131"]),mean(evoWT_set_tbl[,"cluster_71"]),sd(evoWT_set_tbl[,"cluster_71"]),mean(evoWT_set_tbl[,"cluster_320"]),sd(evoWT_set_tbl[,"cluster_320"]),mean(mut_set_tbl[,"cluster_142"]),sd(mut_set_tbl[,"cluster_142"]),mean(mut_set_tbl[,"cluster_6"]),sd(mut_set_tbl[,"cluster_6"]),mean(mut_set_tbl[,"cluster_131"]),sd(mut_set_tbl[,"cluster_131"]),mean(mut_set_tbl[,"cluster_71"]),sd(mut_set_tbl[,"cluster_71"]),mean(mut_set_tbl[,"cluster_320"]),sd(mut_set_tbl[,"cluster_320"])), nrow= 5, ncol=10, byrow = TRUE))%>%`colnames<-`(c("Cystein_mean","Cystein_sd", "Spermidine_mean", "Spermidine_sd","Homoserine_mean","Homoserine_sd", "Methyltioadenosine_mean", "Methyltioadenosine_sd","Putrescine_mean","Putrescine_sd"))%>%add_column(bacteria_type = c("WT","unevolved","evolved","evoWT","mut")) #%>%t()



Cystein <- ggplot(mean_sd_addiotinal_metabolites, aes(x= factor(bacteria_type, levels=c("WT","unevolved","evolved","evoWT","mut")), y=Cystein_mean, fill=bacteria_type)) +
  geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +
  geom_errorbar(aes(ymin=Cystein_mean-Cystein_sd, ymax=Cystein_mean+Cystein_sd), width=.2)+
  labs(title="Cystein\n")+theme_minimal(base_size = 15)+theme(axis.text.x = element_text(face="bold"),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevolved="#339900",evolved="cornflowerblue",evoWT="#d11141",mut="#9999CC"))+scale_x_discrete(limits = c("WT", "unevolved", "evolved","evoWT","mut"))


Spermidine <- ggplot(mean_sd_addiotinal_metabolites, aes(x= factor(bacteria_type, levels=c("WT","unevolved","evolved","evoWT","mut")), y=Spermidine_mean, fill=bacteria_type)) +
  geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +
  geom_errorbar(aes(ymin=Spermidine_mean-Spermidine_sd, ymax=Spermidine_mean+Spermidine_sd), width=.2)+
  labs(title="Spermidine\n")+theme_minimal(base_size = 15)+theme(axis.text.x = element_text(face="bold"),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevolved="#339900",evolved="cornflowerblue",evoWT="#d11141",mut="#9999CC"))+scale_x_discrete(limits = c("WT", "unevolved", "evolved","evoWT","mut"))



Homoserine <- ggplot(mean_sd_addiotinal_metabolites, aes(x= factor(bacteria_type, levels=c("WT","unevolved","evolved","evoWT","mut")), y=Homoserine_mean, fill=bacteria_type)) +
  geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +
  geom_errorbar(aes(ymin=Homoserine_mean-Homoserine_sd, ymax=Homoserine_mean+Homoserine_sd), width=.2)+
  labs(title="Homoserine\n")+theme_minimal(base_size = 15)+theme(axis.text.x = element_text(face="bold"),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevolved="#339900",evolved="cornflowerblue",evoWT="#d11141",mut="#9999CC"))+scale_x_discrete(limits = c("WT", "unevolved", "evolved","evoWT","mut"))

Methyltioadenosine <- ggplot(mean_sd_addiotinal_metabolites, aes(x= factor(bacteria_type, levels=c("WT","unevolved","evolved","evoWT","mut")), y=Methyltioadenosine_mean, fill=bacteria_type)) +
  geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +
  geom_errorbar(aes(ymin=Methyltioadenosine_mean-Methyltioadenosine_sd, ymax=Methyltioadenosine_mean+Methyltioadenosine_sd), width=.2)+
  labs(title="Methyltioadenosine\n")+theme_minimal(base_size = 15)+theme(axis.text.x = element_text(face="bold"),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevolved="#339900",evolved="cornflowerblue",evoWT="#d11141",mut="#9999CC"))+scale_x_discrete(limits = c("WT", "unevolved", "evolved","evoWT","mut"))

Putrescine <- ggplot(mean_sd_addiotinal_metabolites, aes(x= factor(bacteria_type, levels=c("WT","unevolved","evolved","evoWT","mut")), y=Putrescine_mean, fill=bacteria_type)) +
  geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +
  geom_errorbar(aes(ymin=Putrescine_mean-Putrescine_sd, ymax=Putrescine_mean+Putrescine_sd), width=.2)+
  labs(title="Putrescine\n")+theme_minimal(base_size = 15)+theme(axis.text.x = element_text(face="bold"),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevolved="#339900",evolved="cornflowerblue",evoWT="#d11141",mut="#9999CC"))+scale_x_discrete(limits = c("WT", "unevolved", "evolved","evoWT","mut"))


mean_sd_meth_SAM_2 <- data.frame(matrix(c(mean(WT_set_tbl[,"cluster_34"]),sd(WT_set_tbl[,"cluster_34"]),mean(WT_set_tbl[,"cluster_82"]),sd(WT_set_tbl[,"cluster_82"]),mean(unevo_set_tbl[,"cluster_34"]),sd(unevo_set_tbl[,"cluster_34"]),mean(unevo_set_tbl[,"cluster_82"]),sd(unevo_set_tbl[,"cluster_82"]),mean(evo_set_tbl[,"cluster_34"]),sd(evo_set_tbl[,"cluster_34"]),mean(evo_set_tbl[,"cluster_82"]),sd(evo_set_tbl[,"cluster_82"]),mean(evoWT_set_tbl[,"cluster_34"]),sd(evoWT_set_tbl[,"cluster_34"]),mean(evoWT_set_tbl[,"cluster_82"]),sd(evoWT_set_tbl[,"cluster_82"]),
mean(mut_set_tbl[,"cluster_34"]),sd(mut_set_tbl[,"cluster_34"]),mean(mut_set_tbl[,"cluster_82"]),sd(mut_set_tbl[,"cluster_82"])), nrow= 5, ncol=4, byrow = TRUE))%>%`colnames<-`(c("meth_mean","meth_sd", "SAM_mean", "SAM_sd"))%>%add_column(bacteria_type = c("WT","unevolved","evolved","evoWT","mut"))



SAM <- ggplot(mean_sd_meth_SAM_2, aes(x= factor(bacteria_type, levels=c("WT","unevolved","evolved","evoWT","mut")), y=SAM_mean, fill=bacteria_type)) +
  geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +
  geom_errorbar(aes(ymin=SAM_mean-SAM_sd, ymax=SAM_mean+SAM_sd), width=.2)+labs(title="SAM\n", x="\nBacterial Strain", y="Relative Amount\n")+theme_minimal(base_size = 25)+theme(axis.text.x = element_text(face="bold"),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevolved="#339900",evolved="cornflowerblue",evoWT="#d11141",mut="#9999CC"))+scale_x_discrete(limits = c("WT", "unevolved", "evolved","evoWT","mut"))

ggsave("plots_and_tables/plots/SAM_amounts.pdf", height=7, width=12)

meth <- ggplot(mean_sd_meth_SAM_2, aes(x= factor(bacteria_type, levels=c("WT","unevolved","evolved","evoWT","mut")), y=meth_mean, fill=bacteria_type)) +
  geom_bar(stat="identity", position=position_dodge(),width = 0.7, color="black") +
  geom_errorbar(aes(ymin=meth_mean-meth_sd, ymax=meth_mean+meth_sd), width=.2)+labs(title="Methionine\n", x="\nBacterial Strain", y="Relative Amount\n")+theme_minimal(base_size = 25)+theme(axis.text.x = element_text(face="bold"),legend.position="none")+scale_fill_manual(values=c(WT="coral", unevolved="#339900",evolved="cornflowerblue",evoWT="#d11141",mut="#9999CC"))+scale_x_discrete(limits = c("WT", "unevolved", "evolved","evoWT","mut"))

ggsave("plots_and_tables/plots/meth_amounts.pdf", height=7, width=12)


figure <- ggarrange(SAM+rremove("ylab") + rremove("xlab"), meth+rremove("ylab") + rremove("xlab"), Cystein+ rremove("ylab") + rremove("xlab"),Spermidine+ rremove("ylab") + rremove("xlab"),Homoserine+ rremove("ylab") + rremove("xlab"),Methyltioadenosine+ rremove("ylab") + rremove("xlab"), # remove axis labels from plots
                    labels = NULL,
                    ncol = 3, nrow = 2)+theme(plot.margin = margin(0.5,0.5,0.5,0.5, "cm")) 
figure <- annotate_figure(figure, left = textGrob("Relative Abundances", rot = 90, vjust = 1, gp = gpar(cex = 1.3)),
                bottom = textGrob("Bacterial Strain", gp = gpar(cex = 1.3), vjust = -0.7),top = text_grob("",  color = "black", size = 16))

ggsave("plots_and_tables/plots/amount_of_annotated_metabolites1.pdf",figure, width = 15,height = 6)


```

modules of annotated metabolites
```{r}


WT_info_object_multi <- read_rds("modularity_multi/multi_nets/WT_info_object_multi_PCLRC.RData")
unevo_info_object_multi <- read_rds("modularity_multi/multi_nets/unevo_info_object_multi_PCLRC.RData")
evo_info_object_multi <- read_rds("modularity_multi/multi_nets/evo_info_object_multi_PCLRC.RData")
evoWT_info_object_multi <- read_rds("modularity_multi/multi_nets/evoWT_info_object_multi_PCLRC.RData")

modules_WT <- WT_info_object_multi$modules
modules_unevo <- unevo_info_object_multi$modules
modules_evo <- evo_info_object_multi$modules
modules_evoWT <- evoWT_info_object_multi$modules


WT_super <- read_csv("modularity_multi/super_list_WT_PCLRC.csv")%>%select(-starts_with(".")) 
unevo_super <- read_csv("modularity_multi/super_list_unevo_PCLRC.csv")%>%select(-starts_with("."))
evo_super <- read_csv("modularity_multi/super_list_evo_PCLRC.csv")%>%select(-starts_with("."))
evoWT_super <- read_csv("modularity_multi/super_list_evoWT_PCLRC.csv")%>%select(-starts_with("."))

modules_and_roles_WT <- left_join(WT_super,modules_WT, by=c("node_id","layer_id"))#%>%filter(node_name %in% c("cluster_142","cluster_6","cluster_131","cluster_71","cluster_82","cluster_34"))
modules_and_roles_unevo <- left_join(unevo_super,modules_unevo, by=c("node_id","layer_id"))%>%filter(node_name %in% c("cluster_142","cluster_6","cluster_131","cluster_71","cluster_82","cluster_34"))
modules_and_roles_evo <- left_join(evo_super,modules_evo, by=c("node_id","layer_id"))%>%filter(node_name %in% c("cluster_142","cluster_6","cluster_131","cluster_71","cluster_82","cluster_34"))
modules_and_roles_evoWT <- left_join(evoWT_super,modules_evoWT, by=c("node_id","layer_id"))%>%filter(node_name %in% c("cluster_142","cluster_6","cluster_131","cluster_71","cluster_82","cluster_34"))






```

